import type { DeviceFrame } from '../types'

export const devices: DeviceFrame[] = [
  // ── Modern iPhone mockups (vector SVG frames with transparent screens) ──
  {
    id: 'iphone-17-pro-max',
    name: 'iPhone 17 Pro Max',
    category: 'phone',
    width: 462,
    height: 978,
    screenBounds: { x: 11, y: 11, width: 440, height: 956 },
    cornerRadius: 55,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-17-pro-max.svg', dark: '/assets/devices/iphone-17-pro-max.svg' },
    tier: 'free',
    hasDynamicIsland: true,
    dynamicIslandBounds: { x: 164.5, y: 23.33, width: 125, height: 36.67, cornerRadius: 18.335 }
  },
  {
    id: 'iphone-17-pro',
    name: 'iPhone 17 Pro',
    category: 'phone',
    width: 424,
    height: 896,
    screenBounds: { x: 11, y: 11, width: 402, height: 874 },
    cornerRadius: 55,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-17-pro.svg', dark: '/assets/devices/iphone-17-pro.svg' },
    tier: 'free',
    hasDynamicIsland: true,
    dynamicIslandBounds: { x: 143.5, y: 22.33, width: 125, height: 36.67, cornerRadius: 18.335 }
  },
  {
    id: 'iphone-17-pro-max-no-cutout',
    name: 'iPhone 17 Pro Max',
    category: 'phone',
    width: 462,
    height: 978,
    screenBounds: { x: 11, y: 11, width: 440, height: 956 },
    cornerRadius: 55,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-17-pro-max-no-cutout.svg', dark: '/assets/devices/iphone-17-pro-max-no-cutout.svg' },
    tier: 'free',
    noCutoutOf: 'iphone-17-pro-max'
  },
  {
    id: 'iphone-17-pro-no-cutout',
    name: 'iPhone 17 Pro',
    category: 'phone',
    width: 424,
    height: 896,
    screenBounds: { x: 11, y: 11, width: 402, height: 874 },
    cornerRadius: 55,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-17-pro-no-cutout.svg', dark: '/assets/devices/iphone-17-pro-no-cutout.svg' },
    tier: 'free',
    noCutoutOf: 'iphone-17-pro'
  },
  {
    id: 'iphone-16-pro-max',
    name: 'iPhone 16 Pro Max',
    category: 'phone',
    width: 464,
    height: 980,
    screenBounds: { x: 12, y: 12, width: 440, height: 956 },
    cornerRadius: 55,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-16-pro-max.svg', dark: '/assets/devices/iphone-16-pro-max.svg' },
    tier: 'pro',
    hasDynamicIsland: true,
    dynamicIslandBounds: { x: 164.5, y: 23.33, width: 125, height: 36.67, cornerRadius: 18.335 }
  },
  {
    id: 'iphone-16-pro',
    name: 'iPhone 16 Pro',
    category: 'phone',
    width: 417,
    height: 876,
    screenBounds: { x: 12, y: 12, width: 393, height: 852 },
    cornerRadius: 55,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-16-pro.svg', dark: '/assets/devices/iphone-16-pro.svg' },
    tier: 'pro',
    hasDynamicIsland: true,
    dynamicIslandBounds: { x: 144.5, y: 23.33, width: 125, height: 36.67, cornerRadius: 18.335 }
  },
  {
    id: 'iphone-16-pro-max-no-cutout',
    name: 'iPhone 16 Pro Max',
    category: 'phone',
    width: 464,
    height: 980,
    screenBounds: { x: 12, y: 12, width: 440, height: 956 },
    cornerRadius: 55,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-16-pro-max-no-cutout.svg', dark: '/assets/devices/iphone-16-pro-max-no-cutout.svg' },
    tier: 'pro',
    noCutoutOf: 'iphone-16-pro-max'
  },
  {
    id: 'iphone-16-pro-no-cutout',
    name: 'iPhone 16 Pro',
    category: 'phone',
    width: 417,
    height: 876,
    screenBounds: { x: 12, y: 12, width: 393, height: 852 },
    cornerRadius: 55,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-16-pro-no-cutout.svg', dark: '/assets/devices/iphone-16-pro-no-cutout.svg' },
    tier: 'pro',
    noCutoutOf: 'iphone-16-pro'
  },
  {
    id: 'iphone-15-pro-max',
    name: 'iPhone 15 Pro Max',
    category: 'phone',
    width: 460,
    height: 962,
    screenBounds: { x: 15, y: 15, width: 430, height: 932 },
    cornerRadius: 55,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-15-pro-max.svg', dark: '/assets/devices/iphone-15-pro-max.svg' },
    tier: 'pro',
    hasDynamicIsland: true,
    dynamicIslandBounds: { x: 167.5, y: 26.33, width: 125, height: 36.67, cornerRadius: 18.335 }
  },
  {
    id: 'iphone-15-pro',
    name: 'iPhone 15 Pro',
    category: 'phone',
    width: 423,
    height: 882,
    screenBounds: { x: 15, y: 15, width: 393, height: 852 },
    cornerRadius: 55,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-15-pro.svg', dark: '/assets/devices/iphone-15-pro.svg' },
    tier: 'pro',
    hasDynamicIsland: true,
    dynamicIslandBounds: { x: 147.5, y: 26.33, width: 125, height: 36.67, cornerRadius: 18.335 }
  },
  {
    id: 'iphone-15-pro-max-no-cutout',
    name: 'iPhone 15 Pro Max',
    category: 'phone',
    width: 460,
    height: 962,
    screenBounds: { x: 15, y: 15, width: 430, height: 932 },
    cornerRadius: 55,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-15-pro-max-no-cutout.svg', dark: '/assets/devices/iphone-15-pro-max-no-cutout.svg' },
    tier: 'pro',
    noCutoutOf: 'iphone-15-pro-max'
  },
  {
    id: 'iphone-15-pro-no-cutout',
    name: 'iPhone 15 Pro',
    category: 'phone',
    width: 423,
    height: 882,
    screenBounds: { x: 15, y: 15, width: 393, height: 852 },
    cornerRadius: 55,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-15-pro-no-cutout.svg', dark: '/assets/devices/iphone-15-pro-no-cutout.svg' },
    tier: 'pro',
    noCutoutOf: 'iphone-15-pro'
  },
  {
    id: 'iphone-14-pro-max',
    name: 'iPhone 14 Pro Max',
    category: 'phone',
    width: 464,
    height: 966,
    screenBounds: { x: 17, y: 17, width: 430, height: 932 },
    cornerRadius: 56,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-14-pro-max.svg', dark: '/assets/devices/iphone-14-pro-max.svg' },
    tier: 'pro',
    hasDynamicIsland: true,
    dynamicIslandBounds: { x: 169.5, y: 28.33, width: 125, height: 36.67, cornerRadius: 18.335 }
  },
  {
    id: 'iphone-14-pro',
    name: 'iPhone 14 Pro',
    category: 'phone',
    width: 427,
    height: 886,
    screenBounds: { x: 17, y: 17, width: 393, height: 852 },
    cornerRadius: 56,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-14-pro.svg', dark: '/assets/devices/iphone-14-pro.svg' },
    tier: 'pro',
    hasDynamicIsland: true,
    dynamicIslandBounds: { x: 149.5, y: 28.33, width: 125, height: 36.67, cornerRadius: 18.335 }
  },
  {
    id: 'iphone-14-pro-max-no-cutout',
    name: 'iPhone 14 Pro Max',
    category: 'phone',
    width: 464,
    height: 966,
    screenBounds: { x: 17, y: 17, width: 430, height: 932 },
    cornerRadius: 56,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-14-pro-max-no-cutout.svg', dark: '/assets/devices/iphone-14-pro-max-no-cutout.svg' },
    tier: 'pro',
    noCutoutOf: 'iphone-14-pro-max'
  },
  {
    id: 'iphone-14-pro-no-cutout',
    name: 'iPhone 14 Pro',
    category: 'phone',
    width: 427,
    height: 886,
    screenBounds: { x: 17, y: 17, width: 393, height: 852 },
    cornerRadius: 56,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-14-pro-no-cutout.svg', dark: '/assets/devices/iphone-14-pro-no-cutout.svg' },
    tier: 'pro',
    noCutoutOf: 'iphone-14-pro'
  },
  {
    id: 'iphone-13-pro-max',
    name: 'iPhone 13 Pro Max',
    category: 'phone',
    width: 468,
    height: 966,
    screenBounds: { x: 20, y: 20, width: 428, height: 926 },
    cornerRadius: 52,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-13-pro-max.svg', dark: '/assets/devices/iphone-13-pro-max.svg' },
    tier: 'pro'
  },
  {
    id: 'iphone-13-pro',
    name: 'iPhone 13 Pro',
    category: 'phone',
    width: 430,
    height: 884,
    screenBounds: { x: 20, y: 20, width: 390, height: 844 },
    cornerRadius: 52,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-13-pro.svg', dark: '/assets/devices/iphone-13-pro.svg' },
    tier: 'pro'
  },

  // ── Mockup devices (173 devices from high-quality mockup templates) ──
  {
    id: 'iphone-11-black',
    name: 'iPhone 11 Black',
    category: 'phone',
    width: 619,
    height: 1200,
    screenBounds: { x: 60, y: 60, width: 499, height: 1080 },
    cornerRadius: 15,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-11-black.png', dark: '/assets/devices/iphone-11-black.png' },
    tier: 'free'
  },
  {
    id: 'iphone-11-green',
    name: 'iPhone 11 Green',
    category: 'phone',
    width: 619,
    height: 1200,
    screenBounds: { x: 60, y: 60, width: 499, height: 1080 },
    cornerRadius: 15,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-11-green.png', dark: '/assets/devices/iphone-11-green.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-11-pro-gold',
    name: 'iPhone 11 Pro Gold',
    category: 'phone',
    width: 616,
    height: 1200,
    screenBounds: { x: 58, y: 58, width: 500, height: 1084 },
    cornerRadius: 15,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-11-pro-gold.png', dark: '/assets/devices/iphone-11-pro-gold.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-11-pro-max-gold',
    name: 'iPhone 11 Pro Max Gold',
    category: 'phone',
    width: 611,
    height: 1200,
    screenBounds: { x: 53, y: 53, width: 505, height: 1094 },
    cornerRadius: 14,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-11-pro-max-gold.png', dark: '/assets/devices/iphone-11-pro-max-gold.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-11-pro-max-midnight-green',
    name: 'iPhone 11 Pro Max Midnight Green',
    category: 'phone',
    width: 611,
    height: 1200,
    screenBounds: { x: 53, y: 53, width: 505, height: 1094 },
    cornerRadius: 14,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-11-pro-max-midnight-green.png', dark: '/assets/devices/iphone-11-pro-max-midnight-green.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-11-pro-max-silver',
    name: 'iPhone 11 Pro Max Silver',
    category: 'phone',
    width: 611,
    height: 1200,
    screenBounds: { x: 53, y: 53, width: 505, height: 1094 },
    cornerRadius: 14,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-11-pro-max-silver.png', dark: '/assets/devices/iphone-11-pro-max-silver.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-11-pro-max-space-grey',
    name: 'iPhone 11 Pro Max Space Grey',
    category: 'phone',
    width: 611,
    height: 1200,
    screenBounds: { x: 53, y: 53, width: 505, height: 1094 },
    cornerRadius: 14,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-11-pro-max-space-grey.png', dark: '/assets/devices/iphone-11-pro-max-space-grey.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-11-pro-midnight-green',
    name: 'iPhone 11 Pro Midnight Green',
    category: 'phone',
    width: 616,
    height: 1200,
    screenBounds: { x: 58, y: 58, width: 500, height: 1084 },
    cornerRadius: 15,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-11-pro-midnight-green.png', dark: '/assets/devices/iphone-11-pro-midnight-green.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-11-pro-silver',
    name: 'iPhone 11 Pro Silver',
    category: 'phone',
    width: 616,
    height: 1200,
    screenBounds: { x: 58, y: 58, width: 500, height: 1084 },
    cornerRadius: 15,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-11-pro-silver.png', dark: '/assets/devices/iphone-11-pro-silver.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-11-pro-space-grey',
    name: 'iPhone 11 Pro Space Grey',
    category: 'phone',
    width: 616,
    height: 1200,
    screenBounds: { x: 58, y: 58, width: 500, height: 1084 },
    cornerRadius: 15,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-11-pro-space-grey.png', dark: '/assets/devices/iphone-11-pro-space-grey.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-11-purple',
    name: 'iPhone 11 Purple',
    category: 'phone',
    width: 619,
    height: 1200,
    screenBounds: { x: 60, y: 60, width: 499, height: 1080 },
    cornerRadius: 15,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-11-purple.png', dark: '/assets/devices/iphone-11-purple.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-11-red',
    name: 'iPhone 11 Red',
    category: 'phone',
    width: 619,
    height: 1200,
    screenBounds: { x: 60, y: 60, width: 499, height: 1080 },
    cornerRadius: 15,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-11-red.png', dark: '/assets/devices/iphone-11-red.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-11-white',
    name: 'iPhone 11 White',
    category: 'phone',
    width: 619,
    height: 1200,
    screenBounds: { x: 60, y: 60, width: 499, height: 1080 },
    cornerRadius: 15,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-11-white.png', dark: '/assets/devices/iphone-11-white.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-11-yellow',
    name: 'iPhone 11 Yellow',
    category: 'phone',
    width: 619,
    height: 1200,
    screenBounds: { x: 60, y: 60, width: 499, height: 1080 },
    cornerRadius: 15,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-11-yellow.png', dark: '/assets/devices/iphone-11-yellow.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-5c-blue',
    name: 'iPhone 5c Blue',
    category: 'phone',
    width: 573,
    height: 1200,
    screenBounds: { x: 50, y: 179, width: 478, height: 849 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-5c-blue.png', dark: '/assets/devices/iphone-5c-blue.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-5c-green',
    name: 'iPhone 5c Green',
    category: 'phone',
    width: 573,
    height: 1200,
    screenBounds: { x: 50, y: 179, width: 478, height: 849 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-5c-green.png', dark: '/assets/devices/iphone-5c-green.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-5c-red',
    name: 'iPhone 5c Red',
    category: 'phone',
    width: 573,
    height: 1200,
    screenBounds: { x: 50, y: 179, width: 478, height: 849 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-5c-red.png', dark: '/assets/devices/iphone-5c-red.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-5c-white',
    name: 'iPhone 5c White',
    category: 'phone',
    width: 573,
    height: 1200,
    screenBounds: { x: 50, y: 179, width: 478, height: 849 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-5c-white.png', dark: '/assets/devices/iphone-5c-white.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-5c-yellow',
    name: 'iPhone 5c Yellow',
    category: 'phone',
    width: 573,
    height: 1200,
    screenBounds: { x: 50, y: 179, width: 478, height: 849 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-5c-yellow.png', dark: '/assets/devices/iphone-5c-yellow.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-5s-gold',
    name: 'iPhone 5s Gold',
    category: 'phone',
    width: 571,
    height: 1200,
    screenBounds: { x: 48, y: 179, width: 481, height: 853 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-5s-gold.png', dark: '/assets/devices/iphone-5s-gold.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-5s-silver',
    name: 'iPhone 5s Silver',
    category: 'phone',
    width: 571,
    height: 1200,
    screenBounds: { x: 23, y: 179, width: 533, height: 1013 },
    cornerRadius: 25,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-5s-silver.png', dark: '/assets/devices/iphone-5s-silver.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-5s-space-gray',
    name: 'iPhone 5s Space Gray',
    category: 'phone',
    width: 571,
    height: 1200,
    screenBounds: { x: 48, y: 179, width: 481, height: 853 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-5s-space-gray.png', dark: '/assets/devices/iphone-5s-space-gray.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-6s-gold',
    name: 'iPhone 6s Gold',
    category: 'phone',
    width: 614,
    height: 1200,
    screenBounds: { x: 74, y: 186, width: 466, height: 828 },
    cornerRadius: 9,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-6s-gold.png', dark: '/assets/devices/iphone-6s-gold.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-6s-plus-gold',
    name: 'iPhone 6s Plus Gold',
    category: 'phone',
    width: 589,
    height: 1200,
    screenBounds: { x: 42, y: 153, width: 505, height: 900 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-6s-plus-gold.png', dark: '/assets/devices/iphone-6s-plus-gold.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-6s-plus-rose-gold',
    name: 'iPhone 6s Plus Rose Gold',
    category: 'phone',
    width: 589,
    height: 1200,
    screenBounds: { x: 42, y: 153, width: 505, height: 900 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-6s-plus-rose-gold.png', dark: '/assets/devices/iphone-6s-plus-rose-gold.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-6s-plus-silver',
    name: 'iPhone 6s Plus Silver',
    category: 'phone',
    width: 589,
    height: 1200,
    screenBounds: { x: 42, y: 153, width: 505, height: 900 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-6s-plus-silver.png', dark: '/assets/devices/iphone-6s-plus-silver.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-6s-plus-space-gray',
    name: 'iPhone 6s Plus Space Gray',
    category: 'phone',
    width: 589,
    height: 1200,
    screenBounds: { x: 42, y: 153, width: 505, height: 900 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-6s-plus-space-gray.png', dark: '/assets/devices/iphone-6s-plus-space-gray.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-6s-rose-gold',
    name: 'iPhone 6s Rose Gold',
    category: 'phone',
    width: 614,
    height: 1200,
    screenBounds: { x: 74, y: 186, width: 466, height: 828 },
    cornerRadius: 9,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-6s-rose-gold.png', dark: '/assets/devices/iphone-6s-rose-gold.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-6s-silver',
    name: 'iPhone 6s Silver',
    category: 'phone',
    width: 614,
    height: 1200,
    screenBounds: { x: 74, y: 186, width: 466, height: 828 },
    cornerRadius: 9,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-6s-silver.png', dark: '/assets/devices/iphone-6s-silver.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-6s-space-gray',
    name: 'iPhone 6s Space Gray',
    category: 'phone',
    width: 614,
    height: 1200,
    screenBounds: { x: 74, y: 186, width: 466, height: 828 },
    cornerRadius: 9,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-6s-space-gray.png', dark: '/assets/devices/iphone-6s-space-gray.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-7-gold',
    name: 'iPhone 7 Gold',
    category: 'phone',
    width: 614,
    height: 1200,
    screenBounds: { x: 74, y: 186, width: 466, height: 828 },
    cornerRadius: 9,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-7-gold.png', dark: '/assets/devices/iphone-7-gold.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-7-jet-black',
    name: 'iPhone 7 Jet Black',
    category: 'phone',
    width: 614,
    height: 1200,
    screenBounds: { x: 74, y: 186, width: 466, height: 828 },
    cornerRadius: 9,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-7-jet-black.png', dark: '/assets/devices/iphone-7-jet-black.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-7-matte-black',
    name: 'iPhone 7 Matte Black',
    category: 'phone',
    width: 614,
    height: 1200,
    screenBounds: { x: 74, y: 186, width: 466, height: 828 },
    cornerRadius: 9,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-7-matte-black.png', dark: '/assets/devices/iphone-7-matte-black.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-7-plus-gold',
    name: 'iPhone 7 Plus Gold',
    category: 'phone',
    width: 649,
    height: 1200,
    screenBounds: { x: 106, y: 210, width: 437, height: 779 },
    cornerRadius: 9,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-7-plus-gold.png', dark: '/assets/devices/iphone-7-plus-gold.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-7-plus-jet-black',
    name: 'iPhone 7 Plus Jet Black',
    category: 'phone',
    width: 649,
    height: 1200,
    screenBounds: { x: 106, y: 210, width: 437, height: 779 },
    cornerRadius: 9,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-7-plus-jet-black.png', dark: '/assets/devices/iphone-7-plus-jet-black.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-7-plus-matte-black',
    name: 'iPhone 7 Plus Matte Black',
    category: 'phone',
    width: 649,
    height: 1200,
    screenBounds: { x: 106, y: 210, width: 437, height: 779 },
    cornerRadius: 9,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-7-plus-matte-black.png', dark: '/assets/devices/iphone-7-plus-matte-black.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-7-plus-rose-gold',
    name: 'iPhone 7 Plus Rose Gold',
    category: 'phone',
    width: 649,
    height: 1200,
    screenBounds: { x: 106, y: 210, width: 437, height: 779 },
    cornerRadius: 9,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-7-plus-rose-gold.png', dark: '/assets/devices/iphone-7-plus-rose-gold.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-7-plus-silver',
    name: 'iPhone 7 Plus Silver',
    category: 'phone',
    width: 649,
    height: 1200,
    screenBounds: { x: 106, y: 210, width: 437, height: 779 },
    cornerRadius: 9,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-7-plus-silver.png', dark: '/assets/devices/iphone-7-plus-silver.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-7-rose-gold',
    name: 'iPhone 7 Rose Gold',
    category: 'phone',
    width: 614,
    height: 1200,
    screenBounds: { x: 74, y: 186, width: 466, height: 828 },
    cornerRadius: 9,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-7-rose-gold.png', dark: '/assets/devices/iphone-7-rose-gold.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-7-silver',
    name: 'iPhone 7 Silver',
    category: 'phone',
    width: 614,
    height: 1200,
    screenBounds: { x: 74, y: 186, width: 466, height: 828 },
    cornerRadius: 9,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-7-silver.png', dark: '/assets/devices/iphone-7-silver.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-8-gold',
    name: 'iPhone 8 Gold',
    category: 'phone',
    width: 602,
    height: 1200,
    screenBounds: { x: 63, y: 177, width: 476, height: 846 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-8-gold.png', dark: '/assets/devices/iphone-8-gold.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-8-plus-gold',
    name: 'iPhone 8 Plus Gold',
    category: 'phone',
    width: 655,
    height: 1200,
    screenBounds: { x: 80, y: 160, width: 495, height: 880 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-8-plus-gold.png', dark: '/assets/devices/iphone-8-plus-gold.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-8-plus-silver',
    name: 'iPhone 8 Plus Silver',
    category: 'phone',
    width: 655,
    height: 1200,
    screenBounds: { x: 80, y: 160, width: 495, height: 880 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-8-plus-silver.png', dark: '/assets/devices/iphone-8-plus-silver.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-8-plus-space-grey',
    name: 'iPhone 8 Plus Space Grey',
    category: 'phone',
    width: 655,
    height: 1200,
    screenBounds: { x: 80, y: 160, width: 495, height: 880 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-8-plus-space-grey.png', dark: '/assets/devices/iphone-8-plus-space-grey.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-8-silver',
    name: 'iPhone 8 Silver',
    category: 'phone',
    width: 602,
    height: 1200,
    screenBounds: { x: 63, y: 177, width: 476, height: 846 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-8-silver.png', dark: '/assets/devices/iphone-8-silver.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-8-space-grey',
    name: 'iPhone 8 Space Grey',
    category: 'phone',
    width: 602,
    height: 1200,
    screenBounds: { x: 63, y: 177, width: 476, height: 846 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-8-space-grey.png', dark: '/assets/devices/iphone-8-space-grey.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-se-gold',
    name: 'iPhone SE Gold',
    category: 'phone',
    width: 594,
    height: 1200,
    screenBounds: { x: 71, y: 198, width: 452, height: 804 },
    cornerRadius: 9,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-se-gold.png', dark: '/assets/devices/iphone-se-gold.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-se-rose-gold',
    name: 'iPhone SE Rose Gold',
    category: 'phone',
    width: 594,
    height: 1200,
    screenBounds: { x: 71, y: 198, width: 452, height: 804 },
    cornerRadius: 9,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-se-rose-gold.png', dark: '/assets/devices/iphone-se-rose-gold.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-se-silver',
    name: 'iPhone SE Silver',
    category: 'phone',
    width: 594,
    height: 1200,
    screenBounds: { x: 71, y: 198, width: 452, height: 804 },
    cornerRadius: 9,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-se-silver.png', dark: '/assets/devices/iphone-se-silver.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-se-space-gray',
    name: 'iPhone SE Space Gray',
    category: 'phone',
    width: 594,
    height: 1200,
    screenBounds: { x: 71, y: 198, width: 452, height: 804 },
    cornerRadius: 9,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-se-space-gray.png', dark: '/assets/devices/iphone-se-space-gray.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-xr-blue',
    name: 'iPhone XR Blue',
    category: 'phone',
    width: 621,
    height: 1200,
    screenBounds: { x: 65, y: 65, width: 491, height: 1062 },
    cornerRadius: 15,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-xr-blue.png', dark: '/assets/devices/iphone-xr-blue.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-xr-coral',
    name: 'iPhone XR Coral',
    category: 'phone',
    width: 621,
    height: 1200,
    screenBounds: { x: 65, y: 65, width: 491, height: 1062 },
    cornerRadius: 15,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-xr-coral.png', dark: '/assets/devices/iphone-xr-coral.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-xr-red',
    name: 'iPhone XR Red',
    category: 'phone',
    width: 621,
    height: 1200,
    screenBounds: { x: 65, y: 65, width: 491, height: 1062 },
    cornerRadius: 15,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-xr-red.png', dark: '/assets/devices/iphone-xr-red.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-xr-silver',
    name: 'iPhone XR Silver',
    category: 'phone',
    width: 621,
    height: 1200,
    screenBounds: { x: 65, y: 65, width: 491, height: 1062 },
    cornerRadius: 15,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-xr-silver.png', dark: '/assets/devices/iphone-xr-silver.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-xr-space-grey',
    name: 'iPhone XR Space Grey',
    category: 'phone',
    width: 621,
    height: 1200,
    screenBounds: { x: 65, y: 65, width: 491, height: 1062 },
    cornerRadius: 15,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-xr-space-grey.png', dark: '/assets/devices/iphone-xr-space-grey.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-xr-yellow',
    name: 'iPhone XR Yellow',
    category: 'phone',
    width: 621,
    height: 1200,
    screenBounds: { x: 65, y: 65, width: 491, height: 1062 },
    cornerRadius: 15,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-xr-yellow.png', dark: '/assets/devices/iphone-xr-yellow.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-xs-gold',
    name: 'iPhone XS Gold',
    category: 'phone',
    width: 621,
    height: 1200,
    screenBounds: { x: 58, y: 54, width: 505, height: 1092 },
    cornerRadius: 16,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-xs-gold.png', dark: '/assets/devices/iphone-xs-gold.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-xs-max-gold',
    name: 'iPhone XS Max Gold',
    category: 'phone',
    width: 615,
    height: 1200,
    screenBounds: { x: 56, y: 56, width: 503, height: 1087 },
    cornerRadius: 14,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-xs-max-gold.png', dark: '/assets/devices/iphone-xs-max-gold.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-xs-max-silver',
    name: 'iPhone XS Max Silver',
    category: 'phone',
    width: 615,
    height: 1200,
    screenBounds: { x: 56, y: 56, width: 503, height: 1087 },
    cornerRadius: 14,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-xs-max-silver.png', dark: '/assets/devices/iphone-xs-max-silver.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-xs-max-space-grey',
    name: 'iPhone XS Max Space Grey',
    category: 'phone',
    width: 615,
    height: 1200,
    screenBounds: { x: 56, y: 56, width: 503, height: 1087 },
    cornerRadius: 14,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-xs-max-space-grey.png', dark: '/assets/devices/iphone-xs-max-space-grey.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-xs-silver',
    name: 'iPhone XS Silver',
    category: 'phone',
    width: 621,
    height: 1200,
    screenBounds: { x: 58, y: 54, width: 505, height: 1092 },
    cornerRadius: 16,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-xs-silver.png', dark: '/assets/devices/iphone-xs-silver.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-xs-space-grey',
    name: 'iPhone XS Space Grey',
    category: 'phone',
    width: 621,
    height: 1200,
    screenBounds: { x: 58, y: 54, width: 505, height: 1092 },
    cornerRadius: 16,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-xs-space-grey.png', dark: '/assets/devices/iphone-xs-space-grey.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-x-silver',
    name: 'iPhone X Silver',
    category: 'phone',
    width: 604,
    height: 1200,
    screenBounds: { x: 60, y: 77, width: 483, height: 1046 },
    cornerRadius: 15,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-x-silver.png', dark: '/assets/devices/iphone-x-silver.png' },
    tier: 'pro'
  },
  {
    id: 'iphone-x-space-grey',
    name: 'iPhone X Space Grey',
    category: 'phone',
    width: 604,
    height: 1200,
    screenBounds: { x: 61, y: 77, width: 482, height: 1046 },
    cornerRadius: 15,
    variants: ['light'],
    assetPath: { light: '/assets/devices/iphone-x-space-grey.png', dark: '/assets/devices/iphone-x-space-grey.png' },
    tier: 'pro'
  },
  {
    id: 'pixel-3-clearly-white',
    name: 'Google Pixel 3 Clearly White',
    category: 'phone',
    width: 582,
    height: 1200,
    screenBounds: { x: 45, y: 109, width: 492, height: 982 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/pixel-3-clearly-white.png', dark: '/assets/devices/pixel-3-clearly-white.png' },
    tier: 'pro'
  },
  {
    id: 'pixel-3-just-black',
    name: 'Google Pixel 3 Just Black',
    category: 'phone',
    width: 582,
    height: 1200,
    screenBounds: { x: 45, y: 109, width: 492, height: 982 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/pixel-3-just-black.png', dark: '/assets/devices/pixel-3-just-black.png' },
    tier: 'pro'
  },
  {
    id: 'pixel-3-not-pink',
    name: 'Google Pixel 3 Not Pink',
    category: 'phone',
    width: 582,
    height: 1200,
    screenBounds: { x: 45, y: 109, width: 492, height: 982 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/pixel-3-not-pink.png', dark: '/assets/devices/pixel-3-not-pink.png' },
    tier: 'pro'
  },
  {
    id: 'pixel-3-xl-clearly-white',
    name: 'Google Pixel 3 XL Clearly White',
    category: 'phone',
    width: 612,
    height: 1200,
    screenBounds: { x: 53, y: 53, width: 506, height: 1042 },
    cornerRadius: 11,
    variants: ['light'],
    assetPath: { light: '/assets/devices/pixel-3-xl-clearly-white.png', dark: '/assets/devices/pixel-3-xl-clearly-white.png' },
    tier: 'pro'
  },
  {
    id: 'pixel-3-xl-just-black',
    name: 'Google Pixel 3 XL Just Black',
    category: 'phone',
    width: 612,
    height: 1200,
    screenBounds: { x: 53, y: 53, width: 506, height: 1042 },
    cornerRadius: 11,
    variants: ['light'],
    assetPath: { light: '/assets/devices/pixel-3-xl-just-black.png', dark: '/assets/devices/pixel-3-xl-just-black.png' },
    tier: 'pro'
  },
  {
    id: 'pixel-3-xl-not-pink',
    name: 'Google Pixel 3 XL Not Pink',
    category: 'phone',
    width: 612,
    height: 1200,
    screenBounds: { x: 53, y: 53, width: 506, height: 1042 },
    cornerRadius: 11,
    variants: ['light'],
    assetPath: { light: '/assets/devices/pixel-3-xl-not-pink.png', dark: '/assets/devices/pixel-3-xl-not-pink.png' },
    tier: 'pro'
  },
  {
    id: 'one-a9-black',
    name: 'HTC One A9 Black',
    category: 'phone',
    width: 587,
    height: 1200,
    screenBounds: { x: 38, y: 137, width: 508, height: 905 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/one-a9-black.png', dark: '/assets/devices/one-a9-black.png' },
    tier: 'pro'
  },
  {
    id: 'one-a9-white',
    name: 'HTC One A9 White',
    category: 'phone',
    width: 587,
    height: 1200,
    screenBounds: { x: 37, y: 137, width: 509, height: 905 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/one-a9-white.png', dark: '/assets/devices/one-a9-white.png' },
    tier: 'pro'
  },
  {
    id: 'one-m8-black',
    name: 'HTC One M8 Black',
    category: 'phone',
    width: 586,
    height: 1200,
    screenBounds: { x: 34, y: 127, width: 516, height: 917 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/one-m8-black.png', dark: '/assets/devices/one-m8-black.png' },
    tier: 'pro'
  },
  {
    id: 'one-m8-gold',
    name: 'HTC One M8 Gold',
    category: 'phone',
    width: 586,
    height: 1200,
    screenBounds: { x: 34, y: 127, width: 516, height: 917 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/one-m8-gold.png', dark: '/assets/devices/one-m8-gold.png' },
    tier: 'pro'
  },
  {
    id: 'one-m8-silver',
    name: 'HTC One M8 Silver',
    category: 'phone',
    width: 586,
    height: 1200,
    screenBounds: { x: 34, y: 127, width: 516, height: 917 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/one-m8-silver.png', dark: '/assets/devices/one-m8-silver.png' },
    tier: 'pro'
  },
  {
    id: 'p8-black',
    name: 'Huawei P8 Black',
    category: 'phone',
    width: 600,
    height: 1200,
    screenBounds: { x: 47, y: 150, width: 506, height: 900 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/p8-black.png', dark: '/assets/devices/p8-black.png' },
    tier: 'pro'
  },
  {
    id: 'p8-white',
    name: 'Huawei P8 White',
    category: 'phone',
    width: 600,
    height: 1200,
    screenBounds: { x: 47, y: 150, width: 506, height: 900 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/p8-white.png', dark: '/assets/devices/p8-white.png' },
    tier: 'pro'
  },
  {
    id: 'lumia-950-black',
    name: 'Microsoft Lumia 950 Black',
    category: 'phone',
    width: 613,
    height: 1200,
    screenBounds: { x: 35, y: 136, width: 537, height: 956 },
    cornerRadius: 11,
    variants: ['light'],
    assetPath: { light: '/assets/devices/lumia-950-black.png', dark: '/assets/devices/lumia-950-black.png' },
    tier: 'pro'
  },
  {
    id: 'lumia-950-white',
    name: 'Microsoft Lumia 950 White',
    category: 'phone',
    width: 613,
    height: 1200,
    screenBounds: { x: 35, y: 136, width: 537, height: 956 },
    cornerRadius: 11,
    variants: ['light'],
    assetPath: { light: '/assets/devices/lumia-950-white.png', dark: '/assets/devices/lumia-950-white.png' },
    tier: 'pro'
  },
  {
    id: 'moto-e-black',
    name: 'Motorola Moto E Black',
    category: 'phone',
    width: 624,
    height: 1200,
    screenBounds: { x: 52, y: 175, width: 512, height: 911 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/moto-e-black.png', dark: '/assets/devices/moto-e-black.png' },
    tier: 'pro'
  },
  {
    id: 'moto-e-white',
    name: 'Motorola Moto E White',
    category: 'phone',
    width: 624,
    height: 1200,
    screenBounds: { x: 52, y: 175, width: 512, height: 911 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/moto-e-white.png', dark: '/assets/devices/moto-e-white.png' },
    tier: 'pro'
  },
  {
    id: 'moto-g',
    name: 'Motorola Moto G',
    category: 'phone',
    width: 620,
    height: 1200,
    screenBounds: { x: 67, y: 169, width: 486, height: 862 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/moto-g.png', dark: '/assets/devices/moto-g.png' },
    tier: 'pro'
  },
  {
    id: 'nexus-4',
    name: 'Nexus 4',
    category: 'phone',
    width: 619,
    height: 1200,
    screenBounds: { x: 30, y: 134, width: 556, height: 926 },
    cornerRadius: 11,
    variants: ['light'],
    assetPath: { light: '/assets/devices/nexus-4.png', dark: '/assets/devices/nexus-4.png' },
    tier: 'pro'
  },
  {
    id: 'nexus-5x',
    name: 'Nexus 5x',
    category: 'phone',
    width: 596,
    height: 1200,
    screenBounds: { x: 26, y: 115, width: 539, height: 958 },
    cornerRadius: 11,
    variants: ['light'],
    assetPath: { light: '/assets/devices/nexus-5x.png', dark: '/assets/devices/nexus-5x.png' },
    tier: 'pro'
  },
  {
    id: 'nexus-6p',
    name: 'Nexus 6P',
    category: 'phone',
    width: 588,
    height: 1200,
    screenBounds: { x: 22, y: 123, width: 541, height: 961 },
    cornerRadius: 11,
    variants: ['light'],
    assetPath: { light: '/assets/devices/nexus-6p.png', dark: '/assets/devices/nexus-6p.png' },
    tier: 'pro'
  },
  {
    id: '220-black',
    name: 'Nokia 220 Black',
    category: 'phone',
    width: 320,
    height: 741,
    screenBounds: { x: 40, y: 96, width: 240, height: 320 },
    cornerRadius: 5,
    variants: ['light'],
    assetPath: { light: '/assets/devices/220-black.png', dark: '/assets/devices/220-black.png' },
    tier: 'pro'
  },
  {
    id: '220-blue',
    name: 'Nokia 220 Blue',
    category: 'phone',
    width: 320,
    height: 741,
    screenBounds: { x: 40, y: 96, width: 240, height: 320 },
    cornerRadius: 5,
    variants: ['light'],
    assetPath: { light: '/assets/devices/220-blue.png', dark: '/assets/devices/220-blue.png' },
    tier: 'pro'
  },
  {
    id: '220-red',
    name: 'Nokia 220 Red',
    category: 'phone',
    width: 320,
    height: 741,
    screenBounds: { x: 40, y: 96, width: 240, height: 320 },
    cornerRadius: 5,
    variants: ['light'],
    assetPath: { light: '/assets/devices/220-red.png', dark: '/assets/devices/220-red.png' },
    tier: 'pro'
  },
  {
    id: '220-white',
    name: 'Nokia 220 White',
    category: 'phone',
    width: 320,
    height: 741,
    screenBounds: { x: 40, y: 96, width: 240, height: 320 },
    cornerRadius: 5,
    variants: ['light'],
    assetPath: { light: '/assets/devices/220-white.png', dark: '/assets/devices/220-white.png' },
    tier: 'pro'
  },
  {
    id: '220-yellow',
    name: 'Nokia 220 Yellow',
    category: 'phone',
    width: 320,
    height: 741,
    screenBounds: { x: 40, y: 96, width: 240, height: 320 },
    cornerRadius: 5,
    variants: ['light'],
    assetPath: { light: '/assets/devices/220-yellow.png', dark: '/assets/devices/220-yellow.png' },
    tier: 'pro'
  },
  {
    id: '230-black',
    name: 'Nokia 230 Black',
    category: 'phone',
    width: 296,
    height: 695,
    screenBounds: { x: 28, y: 67, width: 240, height: 320 },
    cornerRadius: 5,
    variants: ['light'],
    assetPath: { light: '/assets/devices/230-black.png', dark: '/assets/devices/230-black.png' },
    tier: 'pro'
  },
  {
    id: '230-white',
    name: 'Nokia 230 White',
    category: 'phone',
    width: 296,
    height: 695,
    screenBounds: { x: 28, y: 67, width: 240, height: 320 },
    cornerRadius: 5,
    variants: ['light'],
    assetPath: { light: '/assets/devices/230-white.png', dark: '/assets/devices/230-white.png' },
    tier: 'pro'
  },
  {
    id: 'asha-230-230-white',
    name: 'Nokia Asha 230 230 White',
    category: 'phone',
    width: 321,
    height: 551,
    screenBounds: { x: 39, y: 101, width: 240, height: 320 },
    cornerRadius: 5,
    variants: ['light'],
    assetPath: { light: '/assets/devices/asha-230-230-white.png', dark: '/assets/devices/asha-230-230-white.png' },
    tier: 'pro'
  },
  {
    id: 'asha-230-black',
    name: 'Nokia Asha 230 Black',
    category: 'phone',
    width: 321,
    height: 539,
    screenBounds: { x: 39, y: 101, width: 240, height: 320 },
    cornerRadius: 5,
    variants: ['light'],
    assetPath: { light: '/assets/devices/asha-230-black.png', dark: '/assets/devices/asha-230-black.png' },
    tier: 'pro'
  },
  {
    id: 'asha-230-blue',
    name: 'Nokia Asha 230 Blue',
    category: 'phone',
    width: 321,
    height: 539,
    screenBounds: { x: 39, y: 101, width: 240, height: 320 },
    cornerRadius: 5,
    variants: ['light'],
    assetPath: { light: '/assets/devices/asha-230-blue.png', dark: '/assets/devices/asha-230-blue.png' },
    tier: 'pro'
  },
  {
    id: 'asha-230-green',
    name: 'Nokia Asha 230 Green',
    category: 'phone',
    width: 321,
    height: 539,
    screenBounds: { x: 39, y: 101, width: 240, height: 320 },
    cornerRadius: 5,
    variants: ['light'],
    assetPath: { light: '/assets/devices/asha-230-green.png', dark: '/assets/devices/asha-230-green.png' },
    tier: 'pro'
  },
  {
    id: 'asha-230-red',
    name: 'Nokia Asha 230 Red',
    category: 'phone',
    width: 321,
    height: 539,
    screenBounds: { x: 39, y: 101, width: 240, height: 320 },
    cornerRadius: 5,
    variants: ['light'],
    assetPath: { light: '/assets/devices/asha-230-red.png', dark: '/assets/devices/asha-230-red.png' },
    tier: 'pro'
  },
  {
    id: 'asha-230-white',
    name: 'Nokia Asha 230 White',
    category: 'phone',
    width: 321,
    height: 539,
    screenBounds: { x: 39, y: 101, width: 240, height: 320 },
    cornerRadius: 5,
    variants: ['light'],
    assetPath: { light: '/assets/devices/asha-230-white.png', dark: '/assets/devices/asha-230-white.png' },
    tier: 'pro'
  },
  {
    id: 'asha-230-yellow',
    name: 'Nokia Asha 230 Yellow',
    category: 'phone',
    width: 321,
    height: 539,
    screenBounds: { x: 39, y: 101, width: 240, height: 320 },
    cornerRadius: 5,
    variants: ['light'],
    assetPath: { light: '/assets/devices/asha-230-yellow.png', dark: '/assets/devices/asha-230-yellow.png' },
    tier: 'pro'
  },
  {
    id: 'c3-00',
    name: 'Nokia C3 00',
    category: 'phone',
    width: 380,
    height: 751,
    screenBounds: { x: 30, y: 106, width: 320, height: 240 },
    cornerRadius: 6,
    variants: ['light'],
    assetPath: { light: '/assets/devices/c3-00.png', dark: '/assets/devices/c3-00.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-grand-prime-black',
    name: 'Samsung Galaxy Grand Prime Black',
    category: 'phone',
    width: 618,
    height: 1200,
    screenBounds: { x: 71, y: 176, width: 476, height: 847 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-grand-prime-black.png', dark: '/assets/devices/galaxy-grand-prime-black.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-grand-prime-gold',
    name: 'Samsung Galaxy Grand Prime Gold',
    category: 'phone',
    width: 618,
    height: 1200,
    screenBounds: { x: 71, y: 176, width: 476, height: 847 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-grand-prime-gold.png', dark: '/assets/devices/galaxy-grand-prime-gold.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-grand-prime-white',
    name: 'Samsung Galaxy Grand Prime White',
    category: 'phone',
    width: 618,
    height: 1200,
    screenBounds: { x: 71, y: 176, width: 476, height: 847 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-grand-prime-white.png', dark: '/assets/devices/galaxy-grand-prime-white.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-note-5-black',
    name: 'Samsung Galaxy Note 5 Black',
    category: 'phone',
    width: 604,
    height: 1200,
    screenBounds: { x: 25, y: 111, width: 555, height: 986 },
    cornerRadius: 11,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-note-5-black.png', dark: '/assets/devices/galaxy-note-5-black.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-note-5-gold',
    name: 'Samsung Galaxy Note 5 Gold',
    category: 'phone',
    width: 604,
    height: 1200,
    screenBounds: { x: 25, y: 111, width: 555, height: 986 },
    cornerRadius: 11,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-note-5-gold.png', dark: '/assets/devices/galaxy-note-5-gold.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-note-5-pink',
    name: 'Samsung Galaxy Note 5 Pink',
    category: 'phone',
    width: 604,
    height: 1200,
    screenBounds: { x: 25, y: 111, width: 555, height: 986 },
    cornerRadius: 11,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-note-5-pink.png', dark: '/assets/devices/galaxy-note-5-pink.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-note-5-silver-titanium',
    name: 'Samsung Galaxy Note 5 Silver Titanium',
    category: 'phone',
    width: 604,
    height: 1200,
    screenBounds: { x: 25, y: 111, width: 555, height: 986 },
    cornerRadius: 11,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-note-5-silver-titanium.png', dark: '/assets/devices/galaxy-note-5-silver-titanium.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-note-5-white',
    name: 'Samsung Galaxy Note 5 White',
    category: 'phone',
    width: 604,
    height: 1200,
    screenBounds: { x: 25, y: 111, width: 555, height: 986 },
    cornerRadius: 11,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-note-5-white.png', dark: '/assets/devices/galaxy-note-5-white.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-s3',
    name: 'Samsung Galaxy S3',
    category: 'phone',
    width: 657,
    height: 1200,
    screenBounds: { x: 71, y: 143, width: 515, height: 914 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-s3.png', dark: '/assets/devices/galaxy-s3.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-s5-black',
    name: 'Samsung Galaxy S5 Black',
    category: 'phone',
    width: 629,
    height: 1200,
    screenBounds: { x: 57, y: 143, width: 515, height: 915 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-s5-black.png', dark: '/assets/devices/galaxy-s5-black.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-s5-white',
    name: 'Samsung Galaxy S5 White',
    category: 'phone',
    width: 629,
    height: 1200,
    screenBounds: { x: 57, y: 143, width: 515, height: 915 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-s5-white.png', dark: '/assets/devices/galaxy-s5-white.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-s7-black',
    name: 'Samsung Galaxy S7 Black',
    category: 'phone',
    width: 614,
    height: 1200,
    screenBounds: { x: 50, y: 143, width: 514, height: 914 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-s7-black.png', dark: '/assets/devices/galaxy-s7-black.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-s7-gold',
    name: 'Samsung Galaxy S7 Gold',
    category: 'phone',
    width: 614,
    height: 1200,
    screenBounds: { x: 50, y: 143, width: 514, height: 914 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-s7-gold.png', dark: '/assets/devices/galaxy-s7-gold.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-s7-silver',
    name: 'Samsung Galaxy S7 Silver',
    category: 'phone',
    width: 614,
    height: 1200,
    screenBounds: { x: 50, y: 143, width: 514, height: 914 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-s7-silver.png', dark: '/assets/devices/galaxy-s7-silver.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-s7-white',
    name: 'Samsung Galaxy S7 White',
    category: 'phone',
    width: 614,
    height: 1200,
    screenBounds: { x: 50, y: 143, width: 514, height: 914 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-s7-white.png', dark: '/assets/devices/galaxy-s7-white.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-s8-arctic-silver',
    name: 'Samsung Galaxy S8 Arctic Silver',
    category: 'phone',
    width: 547,
    height: 1200,
    screenBounds: { x: 33, y: 106, width: 481, height: 987 },
    cornerRadius: 13,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-s8-arctic-silver.png', dark: '/assets/devices/galaxy-s8-arctic-silver.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-s8-coral-blue',
    name: 'Samsung Galaxy S8 Coral Blue',
    category: 'phone',
    width: 547,
    height: 1200,
    screenBounds: { x: 33, y: 106, width: 481, height: 987 },
    cornerRadius: 13,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-s8-coral-blue.png', dark: '/assets/devices/galaxy-s8-coral-blue.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-s8-maple-gold',
    name: 'Samsung Galaxy S8 Maple Gold',
    category: 'phone',
    width: 547,
    height: 1200,
    screenBounds: { x: 33, y: 106, width: 481, height: 987 },
    cornerRadius: 13,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-s8-maple-gold.png', dark: '/assets/devices/galaxy-s8-maple-gold.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-s8-midnight-black',
    name: 'Samsung Galaxy S8 Midnight Black',
    category: 'phone',
    width: 547,
    height: 1200,
    screenBounds: { x: 33, y: 106, width: 481, height: 987 },
    cornerRadius: 13,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-s8-midnight-black.png', dark: '/assets/devices/galaxy-s8-midnight-black.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-s8-orchid-gray',
    name: 'Samsung Galaxy S8 Orchid Gray',
    category: 'phone',
    width: 547,
    height: 1200,
    screenBounds: { x: 33, y: 106, width: 481, height: 987 },
    cornerRadius: 13,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-s8-orchid-gray.png', dark: '/assets/devices/galaxy-s8-orchid-gray.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-s9-burgundy-red',
    name: 'Samsung Galaxy S9 Burgundy Red',
    category: 'phone',
    width: 572,
    height: 1200,
    screenBounds: { x: 35, y: 84, width: 502, height: 1032 },
    cornerRadius: 13,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-s9-burgundy-red.png', dark: '/assets/devices/galaxy-s9-burgundy-red.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-s9-coral-blue',
    name: 'Samsung Galaxy S9 Coral Blue',
    category: 'phone',
    width: 572,
    height: 1200,
    screenBounds: { x: 35, y: 84, width: 502, height: 1032 },
    cornerRadius: 13,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-s9-coral-blue.png', dark: '/assets/devices/galaxy-s9-coral-blue.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-s9-lilac-purple',
    name: 'Samsung Galaxy S9 Lilac Purple',
    category: 'phone',
    width: 572,
    height: 1200,
    screenBounds: { x: 35, y: 84, width: 502, height: 1032 },
    cornerRadius: 13,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-s9-lilac-purple.png', dark: '/assets/devices/galaxy-s9-lilac-purple.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-s9-midnight-black',
    name: 'Samsung Galaxy S9 Midnight Black',
    category: 'phone',
    width: 572,
    height: 1200,
    screenBounds: { x: 35, y: 84, width: 502, height: 1032 },
    cornerRadius: 13,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-s9-midnight-black.png', dark: '/assets/devices/galaxy-s9-midnight-black.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-s9-sunrise-gold',
    name: 'Samsung Galaxy S9 Sunrise Gold',
    category: 'phone',
    width: 572,
    height: 1200,
    screenBounds: { x: 35, y: 84, width: 502, height: 1032 },
    cornerRadius: 13,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-s9-sunrise-gold.png', dark: '/assets/devices/galaxy-s9-sunrise-gold.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-s9-titanium-gray',
    name: 'Samsung Galaxy S9 Titanium Gray',
    category: 'phone',
    width: 572,
    height: 1200,
    screenBounds: { x: 35, y: 84, width: 502, height: 1032 },
    cornerRadius: 13,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-s9-titanium-gray.png', dark: '/assets/devices/galaxy-s9-titanium-gray.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-s-duos',
    name: 'Samsung Galaxy S Duos',
    category: 'phone',
    width: 574,
    height: 1100,
    screenBounds: { x: 48, y: 156, width: 480, height: 800 },
    cornerRadius: 10,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-s-duos.png', dark: '/assets/devices/galaxy-s-duos.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-y-black',
    name: 'Samsung Galaxy Y Black',
    category: 'phone',
    width: 313,
    height: 553,
    screenBounds: { x: 37, y: 116, width: 240, height: 320 },
    cornerRadius: 5,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-y-black.png', dark: '/assets/devices/galaxy-y-black.png' },
    tier: 'pro'
  },
  {
    id: 'galaxy-y-white',
    name: 'Samsung Galaxy Y White',
    category: 'phone',
    width: 313,
    height: 553,
    screenBounds: { x: 37, y: 116, width: 240, height: 320 },
    cornerRadius: 5,
    variants: ['light'],
    assetPath: { light: '/assets/devices/galaxy-y-white.png', dark: '/assets/devices/galaxy-y-white.png' },
    tier: 'pro'
  },
  {
    id: 'ipad-air-gold',
    name: 'iPad Air Gold',
    category: 'tablet',
    width: 850,
    height: 1200,
    screenBounds: { x: 61, y: 114, width: 728, height: 972 },
    cornerRadius: 15,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ipad-air-gold.png', dark: '/assets/devices/ipad-air-gold.png' },
    tier: 'pro'
  },
  {
    id: 'ipad-air-silver',
    name: 'iPad Air Silver',
    category: 'tablet',
    width: 850,
    height: 1200,
    screenBounds: { x: 61, y: 114, width: 728, height: 972 },
    cornerRadius: 15,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ipad-air-silver.png', dark: '/assets/devices/ipad-air-silver.png' },
    tier: 'pro'
  },
  {
    id: 'ipad-air-space-grey',
    name: 'iPad Air Space Grey',
    category: 'tablet',
    width: 850,
    height: 1200,
    screenBounds: { x: 61, y: 114, width: 728, height: 972 },
    cornerRadius: 15,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ipad-air-space-grey.png', dark: '/assets/devices/ipad-air-space-grey.png' },
    tier: 'pro'
  },
  {
    id: 'ipad-gold',
    name: 'iPad Gold',
    category: 'tablet',
    width: 850,
    height: 1200,
    screenBounds: { x: 66, y: 122, width: 718, height: 956 },
    cornerRadius: 14,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ipad-gold.png', dark: '/assets/devices/ipad-gold.png' },
    tier: 'pro'
  },
  {
    id: 'ipad-mini-gold',
    name: 'iPad Mini Gold',
    category: 'tablet',
    width: 814,
    height: 1200,
    screenBounds: { x: 66, y: 145, width: 682, height: 909 },
    cornerRadius: 14,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ipad-mini-gold.png', dark: '/assets/devices/ipad-mini-gold.png' },
    tier: 'pro'
  },
  {
    id: 'ipad-mini-silver',
    name: 'iPad Mini Silver',
    category: 'tablet',
    width: 814,
    height: 1200,
    screenBounds: { x: 66, y: 145, width: 682, height: 909 },
    cornerRadius: 14,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ipad-mini-silver.png', dark: '/assets/devices/ipad-mini-silver.png' },
    tier: 'pro'
  },
  {
    id: 'ipad-mini-space-grey',
    name: 'iPad Mini Space Grey',
    category: 'tablet',
    width: 814,
    height: 1200,
    screenBounds: { x: 66, y: 145, width: 682, height: 909 },
    cornerRadius: 14,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ipad-mini-space-grey.png', dark: '/assets/devices/ipad-mini-space-grey.png' },
    tier: 'pro'
  },
  {
    id: 'ipad-pro-11-silver-landscape',
    name: 'iPad Pro 11 Silver Landscape',
    category: 'tablet',
    width: 1200,
    height: 890,
    screenBounds: { x: 86, y: 86, width: 1028, height: 718 },
    cornerRadius: 21,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ipad-pro-11-silver-landscape.png', dark: '/assets/devices/ipad-pro-11-silver-landscape.png' },
    tier: 'pro'
  },
  {
    id: 'ipad-pro-11-silver-portrait',
    name: 'iPad Pro 11 Silver Portrait',
    category: 'tablet',
    width: 890,
    height: 1200,
    screenBounds: { x: 86, y: 86, width: 718, height: 1028 },
    cornerRadius: 14,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ipad-pro-11-silver-portrait.png', dark: '/assets/devices/ipad-pro-11-silver-portrait.png' },
    tier: 'pro'
  },
  {
    id: 'ipad-pro-11-space-gray-landscape',
    name: 'iPad Pro 11 Space Gray Landscape',
    category: 'tablet',
    width: 1200,
    height: 890,
    screenBounds: { x: 86, y: 86, width: 1028, height: 718 },
    cornerRadius: 21,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ipad-pro-11-space-gray-landscape.png', dark: '/assets/devices/ipad-pro-11-space-gray-landscape.png' },
    tier: 'pro'
  },
  {
    id: 'ipad-pro-11-space-gray-portrait',
    name: 'iPad Pro 11 Space Gray Portrait',
    category: 'tablet',
    width: 890,
    height: 1200,
    screenBounds: { x: 86, y: 86, width: 718, height: 1028 },
    cornerRadius: 14,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ipad-pro-11-space-gray-portrait.png', dark: '/assets/devices/ipad-pro-11-space-gray-portrait.png' },
    tier: 'pro'
  },
  {
    id: 'ipad-pro-13-silver-landscape',
    name: 'iPad Pro 13 Silver Landscape',
    category: 'tablet',
    width: 1200,
    height: 938,
    screenBounds: { x: 77, y: 77, width: 1046, height: 784 },
    cornerRadius: 21,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ipad-pro-13-silver-landscape.png', dark: '/assets/devices/ipad-pro-13-silver-landscape.png' },
    tier: 'pro'
  },
  {
    id: 'ipad-pro-13-silver-portrait',
    name: 'iPad Pro 13 Silver Portrait',
    category: 'tablet',
    width: 938,
    height: 1200,
    screenBounds: { x: 77, y: 77, width: 784, height: 1046 },
    cornerRadius: 16,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ipad-pro-13-silver-portrait.png', dark: '/assets/devices/ipad-pro-13-silver-portrait.png' },
    tier: 'pro'
  },
  {
    id: 'ipad-pro-13-space-gray-landscape',
    name: 'iPad Pro 13 Space Gray Landscape',
    category: 'tablet',
    width: 1200,
    height: 938,
    screenBounds: { x: 77, y: 77, width: 1046, height: 784 },
    cornerRadius: 21,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ipad-pro-13-space-gray-landscape.png', dark: '/assets/devices/ipad-pro-13-space-gray-landscape.png' },
    tier: 'pro'
  },
  {
    id: 'ipad-pro-13-space-gray-portrait',
    name: 'iPad Pro 13 Space Gray Portrait',
    category: 'tablet',
    width: 938,
    height: 1200,
    screenBounds: { x: 77, y: 77, width: 784, height: 1046 },
    cornerRadius: 16,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ipad-pro-13-space-gray-portrait.png', dark: '/assets/devices/ipad-pro-13-space-gray-portrait.png' },
    tier: 'pro'
  },
  {
    id: 'ipad-silver',
    name: 'iPad Silver',
    category: 'tablet',
    width: 850,
    height: 1200,
    screenBounds: { x: 66, y: 122, width: 718, height: 956 },
    cornerRadius: 14,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ipad-silver.png', dark: '/assets/devices/ipad-silver.png' },
    tier: 'pro'
  },
  {
    id: 'ipad-space-grey',
    name: 'iPad Space Grey',
    category: 'tablet',
    width: 850,
    height: 1200,
    screenBounds: { x: 66, y: 122, width: 718, height: 956 },
    cornerRadius: 14,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ipad-space-grey.png', dark: '/assets/devices/ipad-space-grey.png' },
    tier: 'pro'
  },
  {
    id: 'surface-pro-3',
    name: 'Microsoft Surface Pro 3',
    category: 'tablet',
    width: 1200,
    height: 869,
    screenBounds: { x: 103, y: 103, width: 994, height: 663 },
    cornerRadius: 20,
    variants: ['light'],
    assetPath: { light: '/assets/devices/surface-pro-3.png', dark: '/assets/devices/surface-pro-3.png' },
    tier: 'pro'
  },
  {
    id: 'surface-pro-4',
    name: 'Microsoft Surface Pro 4',
    category: 'tablet',
    width: 1200,
    height: 830,
    screenBounds: { x: 89, y: 75, width: 1022, height: 680 },
    cornerRadius: 20,
    variants: ['light'],
    assetPath: { light: '/assets/devices/surface-pro-4.png', dark: '/assets/devices/surface-pro-4.png' },
    tier: 'pro'
  },
  {
    id: 'nexus-9',
    name: 'Nexus 9',
    category: 'tablet',
    width: 859,
    height: 1200,
    screenBounds: { x: 81, y: 136, width: 697, height: 928 },
    cornerRadius: 14,
    variants: ['light'],
    assetPath: { light: '/assets/devices/nexus-9.png', dark: '/assets/devices/nexus-9.png' },
    tier: 'pro'
  },
  {
    id: 'macbook-gold',
    name: 'Macbook Gold',
    category: 'laptop',
    width: 1200,
    height: 705,
    screenBounds: { x: 148, y: 50, width: 903, height: 565 },
    cornerRadius: 20,
    variants: ['light'],
    assetPath: { light: '/assets/devices/macbook-gold.png', dark: '/assets/devices/macbook-gold.png' },
    tier: 'pro'
  },
  {
    id: 'macbook-space-grey',
    name: 'Macbook Space Grey',
    category: 'laptop',
    width: 1200,
    height: 705,
    screenBounds: { x: 148, y: 50, width: 903, height: 564 },
    cornerRadius: 18,
    variants: ['light'],
    assetPath: { light: '/assets/devices/macbook-space-grey.png', dark: '/assets/devices/macbook-space-grey.png' },
    tier: 'pro'
  },
  {
    id: 'macbook-air-13-gold',
    name: 'MacBook Air 13 Gold',
    category: 'laptop',
    width: 1200,
    height: 714,
    screenBounds: { x: 156, y: 80, width: 888, height: 554 },
    cornerRadius: 18,
    variants: ['light'],
    assetPath: { light: '/assets/devices/macbook-air-13-gold.png', dark: '/assets/devices/macbook-air-13-gold.png' },
    tier: 'pro'
  },
  {
    id: 'macbook-air-13-silver',
    name: 'MacBook Air 13 Silver',
    category: 'laptop',
    width: 1200,
    height: 714,
    screenBounds: { x: 156, y: 80, width: 888, height: 554 },
    cornerRadius: 18,
    variants: ['light'],
    assetPath: { light: '/assets/devices/macbook-air-13-silver.png', dark: '/assets/devices/macbook-air-13-silver.png' },
    tier: 'pro'
  },
  {
    id: 'macbook-air-13-space-grey',
    name: 'MacBook Air 13 Space Grey',
    category: 'laptop',
    width: 1200,
    height: 714,
    screenBounds: { x: 156, y: 80, width: 888, height: 554 },
    cornerRadius: 18,
    variants: ['light'],
    assetPath: { light: '/assets/devices/macbook-air-13-space-grey.png', dark: '/assets/devices/macbook-air-13-space-grey.png' },
    tier: 'pro'
  },
  {
    id: 'macbook-pro-13-silver',
    name: 'Macbook Pro 13 Silver',
    category: 'laptop',
    width: 1200,
    height: 763,
    screenBounds: { x: 156, y: 104, width: 888, height: 555 },
    cornerRadius: 18,
    variants: ['light'],
    assetPath: { light: '/assets/devices/macbook-pro-13-silver.png', dark: '/assets/devices/macbook-pro-13-silver.png' },
    tier: 'pro'
  },
  {
    id: 'macbook-pro-13-space-grey',
    name: 'Macbook Pro 13 Space Grey',
    category: 'laptop',
    width: 1200,
    height: 763,
    screenBounds: { x: 156, y: 104, width: 888, height: 555 },
    cornerRadius: 18,
    variants: ['light'],
    assetPath: { light: '/assets/devices/macbook-pro-13-space-grey.png', dark: '/assets/devices/macbook-pro-13-space-grey.png' },
    tier: 'pro'
  },
  {
    id: 'macbook-pro-15-silver',
    name: 'Macbook Pro 15 Silver',
    category: 'laptop',
    width: 1200,
    height: 742,
    screenBounds: { x: 155, y: 93, width: 890, height: 556 },
    cornerRadius: 18,
    variants: ['light'],
    assetPath: { light: '/assets/devices/macbook-pro-15-silver.png', dark: '/assets/devices/macbook-pro-15-silver.png' },
    tier: 'pro'
  },
  {
    id: 'macbook-pro-15-space-grey',
    name: 'Macbook Pro 15 Space Grey',
    category: 'laptop',
    width: 1200,
    height: 742,
    screenBounds: { x: 155, y: 93, width: 890, height: 556 },
    cornerRadius: 18,
    variants: ['light'],
    assetPath: { light: '/assets/devices/macbook-pro-15-space-grey.png', dark: '/assets/devices/macbook-pro-15-space-grey.png' },
    tier: 'pro'
  },
  {
    id: 'imac',
    name: 'iMac',
    category: 'laptop',
    width: 1200,
    height: 1012,
    screenBounds: { x: 49, y: 67, width: 1102, height: 620 },
    cornerRadius: 22,
    variants: ['light'],
    assetPath: { light: '/assets/devices/imac.png', dark: '/assets/devices/imac.png' },
    tier: 'pro'
  },
  {
    id: 'imac-pro',
    name: 'iMac Pro',
    category: 'laptop',
    width: 1200,
    height: 999,
    screenBounds: { x: 68, y: 71, width: 1064, height: 601 },
    cornerRadius: 21,
    variants: ['light'],
    assetPath: { light: '/assets/devices/imac-pro.png', dark: '/assets/devices/imac-pro.png' },
    tier: 'pro'
  },
  {
    id: 'imac-retina',
    name: 'iMac Retina',
    category: 'laptop',
    width: 1200,
    height: 1009,
    screenBounds: { x: 49, y: 64, width: 1102, height: 620 },
    cornerRadius: 22,
    variants: ['light'],
    assetPath: { light: '/assets/devices/imac-retina.png', dark: '/assets/devices/imac-retina.png' },
    tier: 'pro'
  },
  {
    id: 'xps-13',
    name: 'Dell XPS 13',
    category: 'laptop',
    width: 1200,
    height: 706,
    screenBounds: { x: 99, y: 27, width: 1002, height: 563 },
    cornerRadius: 20,
    variants: ['light'],
    assetPath: { light: '/assets/devices/xps-13.png', dark: '/assets/devices/xps-13.png' },
    tier: 'pro'
  },
  {
    id: 'xps-15',
    name: 'Dell XPS 15',
    category: 'laptop',
    width: 1200,
    height: 640,
    screenBounds: { x: 156, y: 30, width: 888, height: 500 },
    cornerRadius: 18,
    variants: ['light'],
    assetPath: { light: '/assets/devices/xps-15.png', dark: '/assets/devices/xps-15.png' },
    tier: 'pro'
  },
  {
    id: 'surface-book',
    name: 'Microsoft Surface Book',
    category: 'laptop',
    width: 1200,
    height: 711,
    screenBounds: { x: 166, y: 54, width: 869, height: 579 },
    cornerRadius: 17,
    variants: ['light'],
    assetPath: { light: '/assets/devices/surface-book.png', dark: '/assets/devices/surface-book.png' },
    tier: 'pro'
  },
  {
    id: 'pro-display-xdr',
    name: 'Pro Display XDR',
    category: 'display',
    width: 1200,
    height: 905,
    screenBounds: { x: 28, y: 28, width: 1144, height: 643 },
    cornerRadius: 23,
    variants: ['light'],
    assetPath: { light: '/assets/devices/pro-display-xdr.png', dark: '/assets/devices/pro-display-xdr.png' },
    tier: 'pro'
  },
  {
    id: 'thunderbolt-display',
    name: 'Thunderbolt Display',
    category: 'display',
    width: 1200,
    height: 929,
    screenBounds: { x: 49, y: 56, width: 1104, height: 621 },
    cornerRadius: 22,
    variants: ['light'],
    assetPath: { light: '/assets/devices/thunderbolt-display.png', dark: '/assets/devices/thunderbolt-display.png' },
    tier: 'pro'
  },
  {
    id: 'ultrasharp-24',
    name: 'Dell UltraSharp 24',
    category: 'display',
    width: 1200,
    height: 1064,
    screenBounds: { x: 16, y: 16, width: 1168, height: 730 },
    cornerRadius: 23,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ultrasharp-24.png', dark: '/assets/devices/ultrasharp-24.png' },
    tier: 'pro'
  },
  {
    id: 'ultrasharp-24-90deg',
    name: 'Dell UltraSharp 24 90deg',
    category: 'display',
    width: 716,
    height: 1200,
    screenBounds: { x: 40, y: 23, width: 638, height: 1022 },
    cornerRadius: 13,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ultrasharp-24-90deg.png', dark: '/assets/devices/ultrasharp-24-90deg.png' },
    tier: 'pro'
  },
  {
    id: 'ultrasharp-27',
    name: 'Dell UltraSharp 27',
    category: 'display',
    width: 1200,
    height: 959,
    screenBounds: { x: 15, y: 27, width: 1170, height: 658 },
    cornerRadius: 23,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ultrasharp-27.png', dark: '/assets/devices/ultrasharp-27.png' },
    tier: 'pro'
  },
  {
    id: 'ultrasharp-27-90deg',
    name: 'Dell UltraSharp 27 90deg',
    category: 'display',
    width: 668,
    height: 1200,
    screenBounds: { x: 37, y: 17, width: 594, height: 1057 },
    cornerRadius: 12,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ultrasharp-27-90deg.png', dark: '/assets/devices/ultrasharp-27-90deg.png' },
    tier: 'pro'
  },
  {
    id: 'ultrasharp-5k-monitor-27',
    name: 'Dell UltraSharp 5K Monitor 27',
    category: 'display',
    width: 1200,
    height: 966,
    screenBounds: { x: 36, y: 39, width: 1128, height: 634 },
    cornerRadius: 23,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ultrasharp-5k-monitor-27.png', dark: '/assets/devices/ultrasharp-5k-monitor-27.png' },
    tier: 'pro'
  },
  {
    id: 'ultrasharp-5k-monitor-27-90deg',
    name: 'Dell UltraSharp 5K Monitor 27 90deg',
    category: 'display',
    width: 696,
    height: 1200,
    screenBounds: { x: 57, y: 39, width: 582, height: 1035 },
    cornerRadius: 12,
    variants: ['light'],
    assetPath: { light: '/assets/devices/ultrasharp-5k-monitor-27-90deg.png', dark: '/assets/devices/ultrasharp-5k-monitor-27-90deg.png' },
    tier: 'pro'
  },
  {
    id: 'w850c',
    name: 'Snony W850C',
    category: 'display',
    width: 1200,
    height: 757,
    screenBounds: { x: 10, y: 20, width: 1176, height: 713 },
    cornerRadius: 24,
    variants: ['light'],
    assetPath: { light: '/assets/devices/w850c.png', dark: '/assets/devices/w850c.png' },
    tier: 'pro'
  },

  // ── Browser frames (kept from original — vector SVGs with light/dark variants) ──
  {
    id: 'browser-chrome',
    name: 'Chrome',
    category: 'browser',
    width: 1200,
    height: 800,
    screenBounds: { x: 1, y: 52, width: 1198, height: 747 },
    cornerRadius: 10,
    variants: ['light', 'dark'],
    assetPath: { light: '/assets/devices/browser-chrome-light.svg', dark: '/assets/devices/browser-chrome-dark.svg' },
    tier: 'free'
  },
  {
    id: 'browser-safari',
    name: 'Safari',
    category: 'browser',
    width: 1200,
    height: 800,
    screenBounds: { x: 1, y: 52, width: 1198, height: 747 },
    cornerRadius: 10,
    variants: ['light', 'dark'],
    assetPath: { light: '/assets/devices/browser-safari-light.svg', dark: '/assets/devices/browser-safari-dark.svg' },
    tier: 'pro'
  },
  {
    id: 'browser-firefox',
    name: 'Firefox',
    category: 'browser',
    width: 1200,
    height: 800,
    screenBounds: { x: 1, y: 52, width: 1198, height: 747 },
    cornerRadius: 10,
    variants: ['light', 'dark'],
    assetPath: { light: '/assets/devices/browser-firefox-light.svg', dark: '/assets/devices/browser-firefox-dark.svg' },
    tier: 'pro'
  },
  {
    id: 'browser-arc',
    name: 'Arc',
    category: 'browser',
    width: 1200,
    height: 800,
    screenBounds: { x: 1, y: 52, width: 1198, height: 747 },
    cornerRadius: 10,
    variants: ['light', 'dark'],
    assetPath: { light: '/assets/devices/browser-arc-light.svg', dark: '/assets/devices/browser-arc-dark.svg' },
    tier: 'pro'
  }
]

export const deviceCategories = [
  { id: 'phone', label: 'Phones', icon: '📱' },
  { id: 'tablet', label: 'Tablets', icon: '📱' },
  { id: 'laptop', label: 'Laptops & Desktops', icon: '💻' },
  { id: 'display', label: 'Displays', icon: '🖥️' },
  { id: 'browser', label: 'Browser', icon: '🌐' }
] as const

export function getDeviceById(id: string): DeviceFrame | undefined {
  return devices.find((d) => d.id === id)
}

export function getDevicesForTier(plan: 'free' | 'pro' | 'lifetime'): DeviceFrame[] {
  if (plan === 'pro' || plan === 'lifetime') return devices
  return devices.filter((d) => d.tier === 'free')
}

export function getDevicesByCategory(category: string): DeviceFrame[] {
  return devices.filter((d) => d.category === category)
}

export function suggestDeviceFromAspectRatio(width: number, height: number): DeviceFrame {
  const ratio = width / height

  if (ratio < 0.65) {
    return devices.find((d) => d.id === 'iphone-17-pro-max') ?? devices[0]
  }
  if (ratio < 1.0) {
    return devices.find((d) => d.category === 'tablet') ?? devices[0]
  }
  if (ratio < 2) {
    return devices.find((d) => d.id === 'browser-chrome') ?? devices[0]
  }
  return devices.find((d) => d.category === 'laptop') ?? devices[0]
}

/**
 * Paints a solid black pill over the Dynamic Island region of a simulator
 * screenshot so that the device frame's hardware artwork is the sole island.
 * The status bar clock/battery on either side of the island remain visible.
 * Returns a new base64 PNG string (same dimensions as input).
 *
 * All Dynamic Island iPhones share the same pill spec per Apple HIG:
 * 126×37pt, centered horizontally, y≈12pt from screen top, full pill radius.
 */
export function blankDynamicIsland(img: HTMLImageElement, device: DeviceFrame): string {
  const canvas = document.createElement('canvas')
  canvas.width = img.naturalWidth
  canvas.height = img.naturalHeight
  const ctx = canvas.getContext('2d')!
  ctx.drawImage(img, 0, 0)

  // Convert logical point spec to device pixels using the screen width ratio
  const pixelRatio = img.naturalWidth / device.screenBounds.width
  const padPt = 2                                    // safety padding (catches anti-aliasing)
  const islandWPx = (126 + padPt * 2) * pixelRatio
  const islandHPx = (37  + padPt * 2) * pixelRatio
  const islandXPx = (img.naturalWidth - islandWPx) / 2
  const islandYPx = Math.max(0, (12 - padPt) * pixelRatio)
  const radius    = islandHPx / 2                    // full pill shape

  ctx.fillStyle = '#000000'
  ctx.beginPath()
  ctx.roundRect(islandXPx, islandYPx, islandWPx, islandHPx, radius)
  ctx.fill()

  return canvas.toDataURL('image/png').split(',')[1]
}
